#!/bin/bash
POSTDATA=dummy
if [ "$1" == "--force" ]; then
	POSTDATA=force=1
fi
TOKEN=$(curl -s -d "grant_type=client_credentials&client_id=system&client_secret=$(</var/lib/mailinabox/api.key)&scope=admin" http://127.0.0.1:10222/oauth/token | python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])")
curl -s -d $POSTDATA -H "Authorization: Bearer $TOKEN" http://127.0.0.1:10222/dns/update
